# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


### Imports

In [ ]:
# Importar numpy 
import numpy as np

### 1. Crear un arreglo de ceros de longitud 12

In [11]:
array_zeros = np.zeros(12)

print(array_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5

In [12]:
# Creo un array de 10 ceros
array1 = np.zeros(10)

# Modifico la posicion 5 para asignar un 10 (es el 6to elemento)
array1[5] = 10

print(array1)

[ 0.  0.  0.  0.  0. 10.  0.  0.  0.  0.]


### 3. Crear un arreglo que tenga los números del 10 al 49

In [3]:
np.arange(10, 50, 1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8

In [17]:
array_2d = np.arange(9).reshape(3, 3)

print("Array 2D: \n", array_2d)

# Dimensiones del array
print("Dimensiones: ", array_2d.ndim)

# Cantidad de elementos del array
print("Cantidad de elementos del array: ", array_2d.size)

Array 2D: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Dimensiones:  2
Cantidad de elementos del array:  9


### 5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza

In [27]:
random_array = np.random.rand(100)

print("Array random: \n", random_array)

# Media
media = np.mean(random_array)
print("Media: ", media)

# Varianza
varianza = np.var(random_array)
print("Varianza: ", varianza)

Array random: 
 [0.79503645 0.31583443 0.08518655 0.95471135 0.95361781 0.99274289
 0.20114916 0.05055051 0.8462455  0.96972866 0.49518861 0.56334563
 0.17827561 0.09513108 0.85076721 0.68526147 0.24726458 0.18140835
 0.65379902 0.75005499 0.91232181 0.6967707  0.01785583 0.76463535
 0.91960084 0.97261173 0.83029909 0.54138723 0.31456986 0.08062815
 0.20917578 0.24647974 0.89632269 0.35801282 0.8546833  0.87336231
 0.77604851 0.22548529 0.38936461 0.22559749 0.36999269 0.04144752
 0.91557677 0.74360375 0.9267349  0.3953549  0.76608671 0.54006295
 0.71270455 0.72331441 0.52817804 0.04754726 0.37764147 0.80347856
 0.74011254 0.66044771 0.97212161 0.62349025 0.38958182 0.9672706
 0.5872699  0.38989043 0.34582688 0.6090881  0.25541824 0.09526474
 0.07329354 0.86444244 0.53664975 0.64612162 0.9178099  0.40641744
 0.89478115 0.06496048 0.64019496 0.86213438 0.71757917 0.88441921
 0.47671034 0.14152713 0.56783863 0.25794454 0.86471528 0.79782986
 0.3431048  0.39849063 0.84458384 0.42797846 0.

### 6. Calcular la media de un arreglo usando np.sum

In [24]:
# Calculo de la suma total de elementos del array
suma_random_array = np.sum(random_array)

# Cantidad de elementos del array
cant_elementos = random_array.size

# Calculo de media del array
media_random_array = suma_random_array / cant_elementos

print("Media: ", media_random_array)

Media:  0.4511638224210738


### 7. Calcular la varianza de un arreglo usando np.sum y np.mean

In [30]:
# Usamos array y media del ejercicio 5

# Calculo de varianza
varianza_manual = np.sum((random_array - media) ** 2) / len(random_array)
print(varianza_manual)

0.08954612901629017


### 8. Crear un array de números aleatorios usando np.random.randn

In [31]:
random_n_array = np.random.randn(100)

print(random_n_array)

[-0.63411355 -0.38338786  1.10050342 -0.10358936 -0.58792121 -0.69786073
  2.21144465  0.53060642  0.97780046 -0.7328461   1.06121015  0.7567015
  0.01294303 -1.41343779  1.15712871 -0.48905819  1.44605082 -0.06557061
 -1.44165975  0.30889206 -0.32145132 -0.93785239  0.21484004  0.62878217
  1.08982829  0.26735301  1.43898867 -0.64483462  0.01743695 -1.19994568
 -0.3953277  -1.09911238  1.60333574 -0.56239523  2.26503614  0.98211359
 -1.94771598 -0.57076611 -0.14236357 -0.5888422  -1.10941482  0.69913578
 -0.56543412  0.95460757  0.481058    0.17969171 -0.43376556  0.93854676
 -0.59128805  1.1206069   0.9518767  -0.24074424 -0.87316183  1.67040331
 -1.06942543  0.95134106  0.53712961  1.75556215 -0.35273498 -0.67375474
 -0.00575178  0.24561414  0.00419565 -1.26750407 -0.09061435 -1.64565889
  0.43982359 -1.3347813   1.13623657 -0.99092623  0.90228738  0.66227913
 -1.71450223 -0.81460446  2.0871157   0.06287416 -0.60196127  0.47266405
  0.17997415  0.21203127 -0.78117496  1.80561171  0.